# Generated by Django 5.0.4 on 2024-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreContents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_caption', models.TextField()),
                ('post_timestamp', models.DateField(auto_now=True)),
                ('post_image', models.ImageField(upload_to='')),
                ('post_likes', models.IntegerField()),
            ],
        ),
    ]
