# Generated by Django 5.0.4 on 2024-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreContents', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='post'),
        ),
    ]
