# Generated by Django 5.0.4 on 2024-07-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreContents', '0006_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
    ]
