# Generated by Django 5.0.4 on 2024-07-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreContents', '0007_rename_post_id_likes_post_rename_user_id_likes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
    ]
