# Generated by Django 5.0.4 on 2024-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreContents', '0011_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilePic'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(null=True),
        ),
    ]
