# Generated by Django 5.0.4 on 2024-08-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreContents', '0014_follow_is_active_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_active',
        ),
    ]
